compras/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from compras.forms import RealizarPedido1, RealizarPedido2
from compras.views import RealizarPedidoWizard, ListaPedidosView, DetallePedidoView

urlpatterns = [
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/$', views.add_carrito, name='addcarrito'),
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/(?P<cantidad>[1-9][0-9]*)/$', views.add_carrito, name='addcarritocant'),
	url(r'^carrito/$', views.ver_carrito, name='vercarrito'),
	url(r'^carrito/eliminar/(?P<producto_id>[0-9]+)/$', views.eliminar_producto_carrito, name='eliminarproductocarrito'),
	url(r'^realizarpedido/$', RealizarPedidoWizard.as_view([RealizarPedido1, RealizarPedido2]), name='realizarpedido'),
	url(r'^pedidos/$', ListaPedidosView.as_view(), name='listapedidos'),
	url(r'^pedido/(?P<id>[0-9]+)/$', DetallePedidoView.as_view(), name='detallepedido'),
	url(r'^pedido/confirmar/(?P<id>[0-9]+)/$', views.confirmar_pedido, name='confirmarpedido'),
	url(r'^pedido/cancelar/(?P<id>[0-9]+)/$', views.cancelar_pedido, name='cancelarpedido'),
	url(r'^pedidocompletado/(?P<id>[0-9]+)/$', views.pedido_completado, name='pedidocompletado'),
	url(r'^buscarpedido/$', views.buscar_pedido, name='buscarpedido'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

productos/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^productos/$', views.lista_productos, name='listaproductos'),
	url(r'^productos/(?P<catid>[0-9]+)/$', views.lista_productos, name='listaproductoscat'),
	url(r'^productos/buscar/(?P<busqueda>.+)/$', views.lista_productos, name='listaproductosbus'),
	url(r'^productos/detalle/(?P<id>[0-9]+)/$', views.detalles_producto, name='detallesproducto'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

tienda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tienda/', include('productos.urls', namespace='productos')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios')),
    url(r'^compras/', include('compras.urls', namespace='compras')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

productos/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

# Create your models here.

@python_2_unicode_compatible
class Categoria(models.Model):
	nombre = models.CharField(max_length=150)
	descripcion = models.TextField()
	activa = models.BooleanField(default=True)

	def __str__(self):
		return self.nombre

@python_2_unicode_compatible
class Producto(models.Model):
	nombre = models.CharField(max_length=255)
	precio = models.DecimalField(max_digits=20, decimal_places=2)
	descripcion = models.TextField()
	stock = models.IntegerField()
	imagen = models.FileField(upload_to='imagenes/productos/')
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre

productos/views.py
from django.shortcuts import render, get_object_or_404
from productos.models import Producto, Categoria
from random import randint
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def lista_productos(request, catid = -1):
	categorias = Categoria.objects.all()

	if catid != -1 and Categoria.objects.filter(pk=catid).count():
		productos = Categoria.objects.get(pk=catid).producto_set.all()
	elif request.GET.get('busqueda'):
		productos = Producto.objects.filter(Q(nombre__icontains=request.GET['busqueda']) | Q(descripcion__icontains=request.GET['busqueda'])).all()
	else:
		productos = Producto.objects.all()

	page = request.GET.get('page')
	paginator = Paginator(productos, 24)

	try:
		productos = paginator.page(page)
	except PageNotAnInteger:
		productos = paginator.page(1)
	except EmptyPage:
		productos = paginator.page(paginator.num_pages)


	return render(request, 'productos/productos_lista.html', { 'productos' : productos, 'categorias' : categorias })

def detalles_producto(request, id):
	producto = get_object_or_404(Producto, pk=id)
	count = producto.categoria.producto_set.count()
	index1 = randint(0, count)
	index2 = randint(0, count)
	while index1 == index2:
		index2 = randint(0, count)

	if index1 > index2:
		relacionados = producto.categoria.producto_set.all()[index2:index1][:5]
	else:
		relacionados = producto.categoria.producto_set.all()[index1:index2][:5]

	return render(request, 'productos/productos_detalle.html', { 'producto' : producto, 'relacionados' : relacionados })

productos/templates/productos/productos_detalle.html
{% extends 'base.html' %}

{% block title %}{{ producto.nombre }}{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<img class="img-rounded img-responsive" src='{{ MEDIA_URL }}{{ producto.imagen }}'/>
	</div>
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-8">
				<h3>{{ producto.nombre }}</h3>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-12">
						<h3 class="pull-right" ng-show="catalog.currentProduct.discounts.length">
							{{ producto.precio }} €
						</h3>
					</div>
				</div>
			</div>			
		</div>
		<div class="row">
		<hr>
			<div class="col-sm-offset-6 col-sm-6">
				<a href="{% url 'compras:addcarrito' producto.id %}" class="btn btn-primary btn-lg btn-block">Comprar <span class="glyphicon glyphicon-shopping-cart"></span></a>
			</div>
		</div>
	</div>	
</div>
<hr>
<div class="row">
	<div class="col-md-8 text-justify">{{ producto.descripcion }}</div>
	<div class="col-md-4" style="background: #FAFAFF; border: 1px solid #EEF">
		<div class="row">
			<div class="col-md-12"><h4>Productos relacionados</h4></div>
		</div>
		{% for rel in relacionados %}
			<div class="row">
				<div class="col-md-6"><a href="{% url 'productos:detallesproducto' id=rel.id %}"><img class="img-rounded img-responsive" src='{{ MEDIA_URL }}{{ rel.imagen }}'/></a></div>
			<div class="col-md-6">
				<div class="row"><div class="col-xs-12"><a href="{% url 'productos:detallesproducto' rel.id %}"><h4>{{ rel.nombre }}</h4></a></div></div>
				<div class="row"><div class="col-xs-12">{{ rel.precio }}€</div></div>
			</div>
			</div>
		{% endfor %}

	</div>
</div>

{% endblock %}

productos/templates/productos/productos_lista.html
{% extends 'base.html' %}

{% block title %}Listado de productos{% endblock %}

{% block content %}

{% load query_transform %}

<div class="row">
	<div class="col-md-6">
		{% if categorias %}
			<h4>Categorias</h4>
			<div class="list-group">
			{% for c in categorias %}
				{% if c.activa == True %}

					<a href="{% url 'productos:listaproductoscat' catid=c.id %}" class="list-group-item">{{ c.nombre }}</a>

				{% endif %}
			{% endfor %}
			</div>
		{% endif %}
	</div>
	<div class="col-md-6">
		<form class="form-inline pull-right" method="GET" action="{% url 'productos:listaproductos' %}">
        <div class="form-group">
          <input name="busqueda" type="text" class="form-control" placeholder="Buscar">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
      </form>
	</div>
</div>



<div class="row">
{% for p in productos %}
	<div class="col-md-4 col-sm-6 col-xs-12">
		<div class="row" style="height:250px; background: #FAFAFF; border: 1px solid #EEF">
			<div class="col-md-6"><a href="{% url 'productos:detallesproducto' id=p.id %}"><img class="img-rounded img-responsive" src='{{ MEDIA_URL }}{{ p.imagen }}'/></a></div>
			<div class="col-md-6">
				<div class="row"><div class="col-xs-12"><a href="{% url 'productos:detallesproducto' p.id %}"><h4>{{ p.nombre }}</h4></a></div></div>
				<div class="row"><div class="col-xs-12">{{ p.precio }}€</div></div>
				<div class="row"><div class="col-xs-12 text-justify">{{ p.descripcion | truncatewords:10 }}</div></div>
			</div>
		</div>
	</div>
{% endfor %}
</div>

<div class="row">
	<div class="col-sm-12 text-center">
		<div class="pagination">
		    <span class="step-links">
		        {% if productos.has_previous %}
		            <a href="?{% query_transform request page=productos.previous_page_number %}">Anterior</a>
		        {% endif %}

		        <span class="current">
		            Página {{ productos.number }} de {{ productos.paginator.num_pages }}.
		        </span>

		        {% if productos.has_next %}
		            <a href="?{% query_transform request page=productos.next_page_number %}">Siguiente</a>
		        {% endif %}
		    </span>
		</div>
	</div>
</div>
{% endblock content %}