home/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

tienda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tienda/', include('productos.urls', namespace='productos')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios')),
    url(r'^compras/', include('compras.urls', namespace='compras')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

usuarios/urls.py
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from usuarios.views import PerfilUsuarioView, NuevaDireccionView, EditarDireccionView, EditarPerfilView, DarBajaView

urlpatterns = [
	url(r'^registro/$', views.registro, name='registro'),
	url(r'^logout/$', views.cerrar_sesion, name='logout'),
	url(r'^perfil/$', PerfilUsuarioView.as_view(), name='perfil'),
	url(r'^perfil/editar/$', EditarPerfilView.as_view(), name='editarperfil'),
	url(r'^direccion/nueva/$', NuevaDireccionView.as_view(), name='nuevadireccion'),
	url(r'^direccion/editar/(?P<direccion_id>[0-9]+)/$', EditarDireccionView.as_view(), name='editardireccion'),
	url(r'^direccion/eliminar/(?P<direccion_id>[0-9]+)/$', views.eliminar_direccion, name='eliminardireccion'),
	url(r'^darbaja/$', DarBajaView.as_view(), name='darbaja'),
	url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

usuarios/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

@python_2_unicode_compatible
class Direccion(models.Model):
	descripcion = models.CharField(max_length=255)
	pais = models.CharField(max_length=70)
	provincia = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=100)
	codigo_postal = models.CharField(max_length=5)
	tel_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="El numero de telefono debe seguir el formato: '+999999999'. Hasta 15 digitos permitidos.")
	telefono = models.CharField(validators=[tel_regex], max_length=15)
	telefono_movil = models.CharField(validators=[tel_regex], max_length=15)
	domicilio = models.CharField(max_length=100)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.descripcion;

usuarios/forms.py
from django.forms import ModelForm
from usuarios.models import Direccion, User
from django import forms

class DireccionForm(ModelForm):
	class Meta:
		model = Direccion
		exclude = ('usuario',)

class UsuarioForm(ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email',)

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from django.views.generic import View
from usuarios.forms import DireccionForm, UsuarioForm
from django.urls import reverse
from usuarios.models import Direccion, User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

def registro(request):
	if request.user.id:
		return redirect(reverse('home:index'))
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect(reverse('usuarios:perfil'))
	else:
		form = UserCreationForm()
	return render(request, 'registration/register.html', { 'form' : form })

@login_required
def cerrar_sesion(request):
	logout(request)
	return redirect(reverse('home:index'))

class PerfilUsuarioView(LoginRequiredMixin, View):
	template_name = 'usuario/perfil.html'
	def get(self, request, *args, **kwargs):
		usuario = request.user
		return render(request, self.template_name, { 'usuario' : usuario })

class NuevaDireccionView(LoginRequiredMixin, View):
	form_class = DireccionForm
	template_name = 'usuario/nueva_direccion.html'

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form, 'new' : True })

	def post(self, request, *args, **kwargs):
		usuario = get_object_or_404(User, pk=request.user.id)
		form = self.form_class(request.POST)
		if form.is_valid():
			direccion = form.save(commit=False)
			direccion.usuario = usuario
			direccion.save()
			return redirect(reverse('usuarios:perfil'))
		return render(request, self.template_name, { 'form' : form , 'new' : True })

class EditarDireccionView(LoginRequiredMixin, View):
	form_class = DireccionForm
	template_name = 'usuario/nueva_direccion.html'

	def get(self, request, *args, **kwargs):
		direccion_id = kwargs['direccion_id']
		direccion = get_object_or_404(Direccion, pk=direccion_id)
		if direccion.usuario != request.user:
			return redirect(reverse('usuarios:perfil'))
		form = self.form_class(instance = direccion)
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		direccion_id = kwargs['direccion_id']
		direccion = get_object_or_404(Direccion, pk=direccion_id)
		if direccion.usuario != request.user:
			return redirect(reverse('usuarios:perfil'))

		form = self.form_class(request.POST, request.FILES, instance=direccion)

		if form.is_valid():
			form.save()
			return redirect(reverse('usuarios:perfil'))
		return render(request, self.template_name, { 'form' : form })

class EditarPerfilView(LoginRequiredMixin, View):
	form_class = UsuarioForm
	template_name = 'usuario/editar_perfil.html'

	def get(self, request, *args, **kwargs):
		form = self.form_class(instance = request.user)
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST, request.FILES, instance = request.user)

		if form.is_valid():
			form.save()
			return redirect(reverse('usuarios:perfil'))
		return render(request, self.template_name, { 'form' : form })

@login_required
def eliminar_direccion(request, direccion_id):
	direccion = get_object_or_404(Direccion, pk=direccion_id)

	if direccion.usuario != request.user:
		return redirect(reverse('usuarios:perfil'))

	direccion.delete()
	return redirect(reverse('usuarios:perfil'))

class DarBajaView(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		return redirect(reverse('usuarios:perfil'))
	def post(self, request, *args, **kwargs):
		user = request.user
		user.is_active = False
		user.save()
		logout(request)
		return redirect(reverse('home:index'))

usuarios/templates/usuario/editar_perfil.html
{% extends "base.html" %}

{% block title %}
Editar mi perfil
{% endblock %}

{% block content %}
	<h3>Editar mi perfil</h3>
	<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
	    {{form.as_p}}
		<p><input type='submit' value='Guardar'></p>
	</form>

{% endblock %}

usuarios/templates/usuario/nueva_direccion.html
{% extends "base.html" %}

{% block title %}
{% if new %}
	Nueva dirección
{% else %}
	Editar dirección
{% endif %}
{% endblock %}

{% block content %}
	{% if new %}
		<h3>Añadir nueva dirección</h3>
	{% else %}
		<h3>Editar dirección</h3>
	{% endif %}
	
	<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
	    {{form.as_p}}
		<p><input type='submit' value='Guardar'></p>
	</form>

{% endblock %}

usuarios/templates/usuario/perfil.html
{% extends 'base.html' %}

{% block title %}Perfil de usuario: {{ usuario.username }}{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-12"><h3>Mi perfil <a href="{% url 'usuarios:editarperfil' %}"><span class="glyphicon glyphicon-pencil"></span></a></h3></div>
</div>
<div class="row">
	<div class="col-md-12">
		<p><strong>Nombre de usuario:</strong> {{ usuario.username }}</p>
		<p><strong>Email:</strong> {{ usuario.email }}</p>
		<p><strong>Nombre:</strong> {{ usuario.first_name }}</p>	
		<p><strong>Apellidos:</strong> {{ usuario.last_name }}</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h3>Mis direcciones  <a href="{% url 'usuarios:nuevadireccion' %}"><span class="glyphicon glyphicon-plus"></span></a></h3>
		{% if usuario.direccion_set.all %}
			<ul>
			{% for dir in usuario.direccion_set.all %}
				<li><a href="{% url 'usuarios:editardireccion' dir.id %}">{{ dir.descripcion }}</a> 
					<a onclick="return confirm('Está seguro de que quiere borrar esta dirección?')" href="{% url 'usuarios:eliminardireccion' dir.id %}">
						<span class="glyphicon glyphicon-remove"></span>
					</a>
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<p>Ninguna</p>
		{% endif %}
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<form method="POST" action="{% url 'usuarios:darbaja' %}">
			{% csrf_token %}
			<small><button type="submit" onclick="return confirm('Está seguro de que desea darse de baja');">Darme de baja</button></small>
			
		</form>
	</div>
</div>

{% endblock %}