compras/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from compras.forms import RealizarPedido1, RealizarPedido2
from compras.views import RealizarPedidoWizard, ListaPedidosView, DetallePedidoView

urlpatterns = [
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/$', views.add_carrito, name='addcarrito'),
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/(?P<cantidad>[1-9][0-9]*)/$', views.add_carrito, name='addcarritocant'),
	url(r'^carrito/$', views.ver_carrito, name='vercarrito'),
	url(r'^carrito/eliminar/(?P<producto_id>[0-9]+)/$', views.eliminar_producto_carrito, name='eliminarproductocarrito'),
	url(r'^realizarpedido/$', RealizarPedidoWizard.as_view([RealizarPedido1, RealizarPedido2]), name='realizarpedido'),
	url(r'^pedidos/$', ListaPedidosView.as_view(), name='listapedidos'),
	url(r'^pedido/(?P<id>[0-9]+)/$', DetallePedidoView.as_view(), name='detallepedido'),
	url(r'^pedido/confirmar/(?P<id>[0-9]+)/$', views.confirmar_pedido, name='confirmarpedido'),
	url(r'^pedido/cancelar/(?P<id>[0-9]+)/$', views.cancelar_pedido, name='cancelarpedido'),
	url(r'^pedidocompletado/(?P<id>[0-9]+)/$', views.pedido_completado, name='pedidocompletado'),
	url(r'^buscarpedido/$', views.buscar_pedido, name='buscarpedido'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

productos/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^productos/$', views.lista_productos, name='listaproductos'),
	url(r'^productos/(?P<catid>[0-9]+)/$', views.lista_productos, name='listaproductoscat'),
	url(r'^productos/buscar/(?P<busqueda>.+)/$', views.lista_productos, name='listaproductosbus'),
	url(r'^productos/detalle/(?P<id>[0-9]+)/$', views.detalles_producto, name='detallesproducto'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

tienda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tienda/', include('productos.urls', namespace='productos')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios')),
    url(r'^compras/', include('compras.urls', namespace='compras')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

compras/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

from usuarios.models import User
from productos.models import Producto

from django.utils import timezone

# Create your models here.

@python_2_unicode_compatible
class MetodoPago(models.Model):
	nombre = models.CharField(max_length=100)
	recargo = models.DecimalField(max_digits=20, decimal_places=2)

	def __str__(self):
		return self.nombre + ", +" + str(self.recargo) + " euros"

@python_2_unicode_compatible
class MetodoEnvio(models.Model):
	nombre = models.CharField(max_length=100)
	coste = models.DecimalField(max_digits=20, decimal_places=2)

	def __str__(self):
		return self.nombre + ", +" + str(self.coste) + " euros"

@python_2_unicode_compatible
class Pedido(models.Model):
	usuario = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
	nombre_cliente = models.CharField(max_length=200)
	apellidos_cliente = models.CharField(max_length=200)
	email_cliente = models.CharField(max_length=255)
	pais = models.CharField(max_length=70)
	provincia = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=100)
	codigo_postal = models.CharField(max_length=5)
	telefono = models.CharField(max_length=15)
	telefono_movil = models.CharField(max_length=15)
	domicilio = models.CharField(max_length=100)

	SIN_CONFIRMAR = 'SC'
	EN_ESPERA = 'ES'
	EN_PREPARACION = 'PR'
	ENVIADO = 'EN'
	CANCELADO = 'CA'

	ESTADOS_PEDIDO = (
			(SIN_CONFIRMAR, 'Sin confirmar'),
			(EN_ESPERA, 'En espera'),
			(EN_PREPARACION, 'En preparacion'),
			(ENVIADO, 'Enviado'),
			(CANCELADO, 'Cancelado'),
		)

	estado = models.CharField(max_length=2, choices=ESTADOS_PEDIDO, default=SIN_CONFIRMAR)
	metodo_pago = models.ForeignKey(MetodoPago, on_delete=models.CASCADE)
	metodo_envio = models.ForeignKey(MetodoEnvio, on_delete=models.CASCADE)
	fecha = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.nombre_cliente + " - " + str(self.id)

@python_2_unicode_compatible
class ProductoPedido(models.Model):
	pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
	producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
	cantidad = models.IntegerField()
	precio = models.DecimalField(max_digits=20, decimal_places=2)

	def __str__(self):
		return self.pedido.nombre_cliente + " - " + str(self.pedido.id) + " - " + self.producto.nombre

compras/forms.py
from compras.models import Pedido, ProductoPedido, MetodoEnvio, MetodoPago
from django import forms
from django.forms import ModelForm

class RealizarPedido1(ModelForm):
	class Meta:
		model = Pedido
		fields = ('nombre_cliente', 'apellidos_cliente', 'email_cliente', 'pais', 'provincia', 
					'ciudad', 'codigo_postal', 'telefono', 'telefono_movil', 'domicilio',)

class RealizarPedido2(ModelForm):
	class Meta:
		model = Pedido
		fields = ('metodo_pago', 'metodo_envio',)

class BuscarPedido(forms.Form):
	idpedido = forms.IntegerField(label = 'Identificador del pedido')

compras/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from productos.models import Producto
from django.utils import timezone
from formtools.wizard.views import SessionWizardView
from compras.models import Pedido, ProductoPedido, MetodoPago, MetodoEnvio, ProductoPedido
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import View

# Create your views here.

def add_carrito(request, producto_id, cantidad = 1):
	producto = get_object_or_404(Producto, pk=producto_id)

	carrito = request.session.get('carrito', {})
	carrito[producto_id] = cantidad
	request.session['carrito'] = carrito	

	return redirect(reverse('compras:vercarrito'))

def ver_carrito(request):
	carrito = request.session.get('carrito', {})
	productos = []
	total = 0
	for k,v in carrito.items():
		if Producto.objects.filter(pk=k).exists():
			producto = get_object_or_404(Producto, pk=k)
			cantidadinc = int(v)+1
			cantidaddec = int(v)-1 if int(v)-1 > 0 else 1
			productos.append({ 'producto' : producto, 'cantidad' : v, 'preciototal' : producto.precio * int(v), 'cantidadinc' : cantidadinc, 'cantidaddec' : cantidaddec })
			total = total + producto.precio * int(v)

	return render(request, 'compras/carrito.html', { 'carrito' : productos, 'total' : total })

def eliminar_producto_carrito(request, producto_id):
	carrito = request.session.get('carrito', {})
	del carrito[producto_id]
	request.session['carrito'] = carrito
	return redirect(reverse('compras:vercarrito'))

class RealizarPedidoWizard(SessionWizardView):
	def done(self, form_list, **kwargs):
		carrito = self.request.session.get('carrito', {})
		if not carrito:
			return HttpResponse('No hay productos en el carrito')
		pedido = form_list[0].instance
		pedido.metodo_pago = form_list[1].instance.metodo_pago
		pedido.metodo_envio = form_list[1].instance.metodo_envio
		if not self.request.user.is_anonymous:
			pedido.usuario = self.request.user
		else:
			pedido.estado = 'ES'
		pedido.save()

		for k,v in carrito.items():
			if Producto.objects.filter(pk=k).exists():	
				producto_pedido = ProductoPedido()
				producto = get_object_or_404(Producto, pk=k)
				producto_pedido.producto = producto
				producto_pedido.cantidad = int(v)
				producto_pedido.precio = producto.precio
				producto_pedido.pedido = pedido
				producto_pedido.save()

		del self.request.session['carrito']

		if not self.request.user.is_anonymous:
			return redirect(reverse('compras:detallepedido', kwargs={ 'id' : pedido.id }))
		else:
			return redirect(reverse('compras:pedidocompletado', kwargs={ 'id' : pedido.id }))


class ListaPedidosView(LoginRequiredMixin, View):
	template_name = 'compras/lista_pedidos.html'

	def get(self, request, *args, **kwargs):
		if request.user:
			pedidos = request.user.pedido_set.all()
			for p in pedidos:
				p.precio = 0
				for prod in p.productopedido_set.all():
					p.precio = p.precio + prod.precio * prod.cantidad
				p.precio = p.precio + p.metodo_pago.recargo + p.metodo_envio.coste
			return render(request, self.template_name, { 'pedidos' : pedidos })
		return redirect(reverse('home:index'))

class DetallePedidoView(View):
	template_name = 'compras/detalle_pedido.html'

	def get(self, request, *args, **kwargs):
		if request.user:
			pedido = get_object_or_404(Pedido, pk=kwargs['id'])
			if (not pedido.usuario and request.user.is_anonymous) or pedido.usuario == request.user:
				productos = pedido.productopedido_set.all()
				subtotal = 0
				for p in productos:
					p.preciototal = p.producto.precio * p.cantidad
					subtotal = subtotal + p.preciototal
				total = subtotal + pedido.metodo_pago.recargo + pedido.metodo_envio.coste
				return render(self.request, self.template_name, { 'pedido' : pedido, 'productos' : productos, 'subtotal' : subtotal, 'total' : total })
			return redirect(reverse('compras:listapedidos'))
		return redirect(reverse('usuarios:login'))		

@login_required
def confirmar_pedido(request, id):
	if request.user:
		pedido = get_object_or_404(Pedido, pk=id)
		if pedido.usuario == request.user and pedido.estado == 'SC':
			pedido.estado = 'ES'
			pedido.save()
		return redirect(reverse('compras:listapedidos'))
	return redirect(reverse('home:login'))

@login_required
def cancelar_pedido(request, id):
	if request.user:
		pedido = get_object_or_404(Pedido, pk=id)
		if pedido.usuario == request.user and (pedido.estado == 'SC' or pedido.estado == 'ES' or pedido.estado == 'PR'):
			pedido.estado = 'CA'
			pedido.save()
		return redirect(reverse('compras:listapedidos'))
	return redirect(reverse('home:login'))

def pedido_completado(request, id):
	return render(request, 'compras/pedido_completado.html', { 'idpedido' : id })

def buscar_pedido(request):
	if request.POST:
		idpedido = request.POST.get('idpedido')
		pedido = get_object_or_404(Pedido, pk=idpedido)
		if not pedido.usuario or request.user == pedido.usuario:
			return redirect(reverse('compras:detallepedido', kwargs={ 'id' : idpedido }))
		else:
			return redirect(reverse('home:index'))

compras/templates/compras/carrito.html
{% extends 'base.html' %}

{% block title %}Carrito de la compra{% endblock %}

{% block content %}
<h3>Artículos en tu carrito</h3>
<div class="row">
	<div class="col-sm-12">
		
		{% if carrito %}
			{% for p in carrito %}
				<div class="row" style="border-bottom:1px solid #EEE;">
					<div class="col-sm-1">
						<a href="{% url 'productos:detallesproducto' id=p.producto.id %}"><img class="img-rounded img-responsive" src="{{ MEDIA_URL }}{{ p.producto.imagen }}" alt="{{ p.producto.nombre }}"/></a>
					</div>
					<div class="col-sm-11">
						<div class="row" style="vertical-align: middle; display:inline">
							<div class="col-sm-7">
								<a href="{% url 'productos:detallesproducto' id=p.producto.id %}">{{ p.producto.nombre }}</a>
							</div>
							<div class="col-sm-2">
								<a href="{% url 'compras:addcarritocant' producto_id=p.producto.id cantidad=p.cantidaddec %}"><span class="glyphicon glyphicon-minus"></span></a> {{ p.cantidad }} ud. <a href="{% url 'compras:addcarritocant' producto_id=p.producto.id cantidad=p.cantidadinc %}"><span class="glyphicon glyphicon-plus"></span></a>
							</div>
							<div class="col-sm-1">{{ p.producto.precio }}€</div>
							<div class="col-sm-1">{{ p.preciototal }}€</div>
							<div class="col-sm-1"><a href="{% url 'compras:eliminarproductocarrito' p.producto.id %}"><span class="glyphicon glyphicon-trash"></span></a></div>
						</div>
					</div>
				</div>
			{% endfor %}
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-11">
					<div class="row" style="vertical-align: top; display:inline">
						<div class="col-sm-2"><strong>TOTAL</strong></div>
						<div class="col-sm-offset-8 col-sm-1">
							<strong>{{ total }}€</strong>
						</div>
						<div class="col-sm-1"></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12"><br></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<a class="btn btn-primary pull-right" href="{% url 'compras:realizarpedido' %}">Realizar pedido</a>
				</div>
			</div>

		{% else %}
			<p>El carrito está vacío.</p>
		{% endif %}

	</div>
</div>


{% endblock content %}

compras/templates/compras/detalle_pedido.html
{% extends 'base.html' %}

{% block title %}Detalle del pedido #{{ pedido.id }}{% endblock %}

{% block content %}
<h3>Detalle del pedido #{{ pedido.id }}</h3>
<div class="row">
	<div class="col-sm-6">	
		<h4>Datos del cliente</h4>
		<p>Nombre: {{ pedido.nombre_cliente }}</p>
		<p>Apellidos: {{ pedido.apellidos_cliente }}</p>
		<p>Email: {{ pedido.email_cliente }}</p>
	</div>
	<div class="col-sm-6" style="border-left:1px solid #EEE">
		<h4>Información del pedido</h4>
		<p>Estado: {{ pedido.get_estado_display }}</p>
		<p>Método de pago: {{ pedido.metodo_pago }}</p>
		<p>Forma de envío: {{ pedido.metodo_envio }}</p>
		<p>Fecha de creación: {{ pedido.fecha | date:'d-m-Y H:i' }}</p>	
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<h4>Dirección de envío</h4>
		<p>País: {{ pedido.pais }}</p>
		<p>Provincia: {{ pedido.provincia }}</p>
		<p>Ciudad: {{ pedido.ciudad }}</p>
		<p>Código postal: {{ pedido.codigo_postal }}</p>
		<p>Teléfono: {{ pedido.telefono }}</p>
		<p>Teléfono móvil: {{ pedido.telefono_movil }}</p>
		<p>Domicilio: {{ pedido.domicilio }}</p>
	</div>
	<div class="col-sm-6">
		{% if not request.user.is_anonymous %}
			{% if pedido.estado == 'ES' or pedido.estado == 'PR' or pedido.estado == 'SC' %}<a class="btn btn-danger" href="{% url 'compras:cancelarpedido' id=pedido.id %}">Cancelar pedido</a>{% endif %}
			{% if pedido.estado == 'SC' %}<a class="btn btn-success" href="{% url 'compras:confirmarpedido' id=pedido.id %}">Confirmar pedido</a>{% endif %}
		{% endif %}
	</div>
</div>
<hr>

{% for p in productos %}
		<div class="row" style="border-bottom:1px solid #EEE;">
			<div class="col-sm-1">
				<a href="{% url 'productos:detallesproducto' id=p.producto.id %}"><img class="img-rounded img-responsive" src="{{ MEDIA_URL }}{{ p.producto.imagen }}" alt="{{ p.producto.nombre }}"/></a>
			</div>
			<div class="col-sm-11">
				<div class="row" style="vertical-align: middle; display:inline">
					<div class="col-sm-7">
						<a href="{% url 'productos:detallesproducto' id=p.producto.id %}">{{ p.producto.nombre }}</a>
					</div>
					<div class="col-sm-2">
						{{ p.cantidad }} ud.
					</div>
					<div class="col-sm-1">{{ p.producto.precio }}€</div>
					<div class="col-sm-2">{{ p.preciototal }}€</div>
				</div>
			</div>
		</div>
{% endfor %}
<div class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-11">
		<div class="row" style="vertical-align: top; display:inline">
			<div class="col-sm-2"><strong>Subtotal</strong></div>
			<div class="col-sm-offset-8 col-sm-1">
				<strong>{{ subtotal }}€</strong>
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-11">
		<div class="row" style="vertical-align: top; display:inline">
			<div class="col-sm-2">{{ pedido.metodo_pago.nombre }}</div>
			<div class="col-sm-offset-8 col-sm-1">
				+{{ pedido.metodo_pago.recargo }}€
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-11">
		<div class="row" style="vertical-align: top; display:inline">
			<div class="col-sm-2">{{ pedido.metodo_envio.nombre }}</div>
			<div class="col-sm-offset-8 col-sm-1">
				+{{ pedido.metodo_envio.coste }}€
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-11">
		<div class="row" style="vertical-align: top; display:inline">
			<div class="col-sm-2"><strong>TOTAL</strong></div>
			<div class="col-sm-offset-8 col-sm-1">
				<strong>{{ total }}€</strong>
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>
</div>

{% endblock %}

compras/templates/compras/lista_pedidos.html
{% extends 'base.html' %}

{% block title %}Historial de pedidos{% endblock %}

{% block content %}
<h3>Historial de pedidos</h3>
{% if pedidos %}
		<div class="row" style="border-bottom: 1px solid #EEE">
				<div class="col-sm-2 text-center">Nº pedido</div>
				<div class="col-sm-5">Fecha de creación</div>
				<div class="col-sm-2 text-right">Precio total</div>
				<div class="col-sm-offset-1 col-sm-2">Estado</div>
		</div>
		{% for p in pedidos %}
			<a href="{% url 'compras:detallepedido' id=p.id %}">
			<div class="row" style="border-bottom: 1px solid #EEE">
				<div class="col-sm-2 text-center">#{{ p.id }}</div>
				<div class="col-sm-5">{{ p.fecha | date:'d-m-Y H:i' }}</div>
				<div class="col-sm-2 text-right">{{ p.precio }}€</div>
				<div class="col-sm-offset-1 col-sm-2">{{ p.get_estado_display }}</div>
			</div>
			</a>
		{% endfor %}
{% else %}
	<p>No has realizado ningún pedido</p>
{% endif %}
{% endblock %}

compras/templates/compras/pedido_completado.html
{% extends 'base.html' %}

{% block title %}Pedido completado{% endblock %}

{% block content %}
<h3>Pedido completado correctamente</h3>
<p>El identificador de su pedido es {{ idpedido }}. Es recomendable que lo guarde ya que le será necesario para consultar el estado del
pedido en cualquier momento.</p>
<p><a href="{% url 'compras:detallepedido' id=idpedido %}">Ir al pedido</a></p>
{% endblock %}