compras/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from compras.forms import RealizarPedido1, RealizarPedido2
from compras.views import RealizarPedidoWizard, ListaPedidosView, DetallePedidoView

urlpatterns = [
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/$', views.add_carrito, name='addcarrito'),
	url(r'^carrito/add/(?P<producto_id>[0-9]+)/(?P<cantidad>[1-9][0-9]*)/$', views.add_carrito, name='addcarritocant'),
	url(r'^carrito/$', views.ver_carrito, name='vercarrito'),
	url(r'^carrito/eliminar/(?P<producto_id>[0-9]+)/$', views.eliminar_producto_carrito, name='eliminarproductocarrito'),
	url(r'^realizarpedido/$', RealizarPedidoWizard.as_view([RealizarPedido1, RealizarPedido2]), name='realizarpedido'),
	url(r'^pedidos/$', ListaPedidosView.as_view(), name='listapedidos'),
	url(r'^pedido/(?P<id>[0-9]+)/$', DetallePedidoView.as_view(), name='detallepedido'),
	url(r'^pedido/confirmar/(?P<id>[0-9]+)/$', views.confirmar_pedido, name='confirmarpedido'),
	url(r'^pedido/cancelar/(?P<id>[0-9]+)/$', views.cancelar_pedido, name='cancelarpedido'),
	url(r'^pedidocompletado/(?P<id>[0-9]+)/$', views.pedido_completado, name='pedidocompletado'),
	url(r'^buscarpedido/$', views.buscar_pedido, name='buscarpedido'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

productos/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^productos/$', views.lista_productos, name='listaproductos'),
	url(r'^productos/(?P<catid>[0-9]+)/$', views.lista_productos, name='listaproductoscat'),
	url(r'^productos/buscar/(?P<busqueda>.+)/$', views.lista_productos, name='listaproductosbus'),
	url(r'^productos/detalle/(?P<id>[0-9]+)/$', views.detalles_producto, name='detallesproducto'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

tienda/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tienda/', include('productos.urls', namespace='productos')),
    url(r'^usuario/', include('usuarios.urls', namespace='usuarios')),
    url(r'^compras/', include('compras.urls', namespace='compras')),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

usuarios/urls.py
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from usuarios.views import PerfilUsuarioView, NuevaDireccionView, EditarDireccionView, EditarPerfilView, DarBajaView

urlpatterns = [
	url(r'^registro/$', views.registro, name='registro'),
	url(r'^logout/$', views.cerrar_sesion, name='logout'),
	url(r'^perfil/$', PerfilUsuarioView.as_view(), name='perfil'),
	url(r'^perfil/editar/$', EditarPerfilView.as_view(), name='editarperfil'),
	url(r'^direccion/nueva/$', NuevaDireccionView.as_view(), name='nuevadireccion'),
	url(r'^direccion/editar/(?P<direccion_id>[0-9]+)/$', EditarDireccionView.as_view(), name='editardireccion'),
	url(r'^direccion/eliminar/(?P<direccion_id>[0-9]+)/$', views.eliminar_direccion, name='eliminardireccion'),
	url(r'^darbaja/$', DarBajaView.as_view(), name='darbaja'),
	url('^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Tienda virtual{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>
<body>

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home:index' %}">Tienda virtual</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'productos:listaproductos' %}">Productos</a></li>
      </ul>
      <form class="navbar-form navbar-left" method="GET" action="{% url 'productos:listaproductos' %}">
        <div class="form-group">
          <input type="text" name="busqueda" class="form-control" placeholder="Buscar productos">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'compras:vercarrito' %}"><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
        {% if user.id %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'usuarios:perfil' %}">Mi perfil</a></li>
            <li><a href="{% url 'compras:listapedidos' %}">Historial de pedidos</a></li>
            <li><a href="{% url 'usuarios:logout' %}">Cerrar sesión</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{% url 'usuarios:registro' %}?next={{ request.path }}">Registrarse <span class="glyphicon glyphicon-edit"></span></a></li>
        <li><a href="{% url 'usuarios:login' %}?next={{ request.path }}">Identificarse <span class="glyphicon glyphicon-log-in"></span></a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock navbar %}
<div class="container">
	{% block content %}{% endblock content %}
</div>
</body>
</html>